---
- name: Searching SSID in MongoDB
  community.mongodb.mongodb_shell:
    login_host: localhost
    login_port: 27117
    db: "ace"
    eval: 'db.wlanconf.find({"name": "{{ wifissid }}"})'
  register: ssid
- set_fact:
    old_wifi_key: "{{ ssid.transformed_output.x_passphrase }}"


- name: Updating wifi key
  community.mongodb.mongodb_shell:
    login_host: localhost
    login_port: 27117
    db: "ace"
    eval: 'db.wlanconf.update({"name" : "{{ wifissid }}"},{$set: {"x_passphrase" : "{{ wifi_key }}"}})'
  register: wifi


- name: Connect to website using previously stored cookie and save devices list
  uri:
    url: https://{{ inventory_hostname }}:8443/api/s/default/stat/device
    method: GET
    return_content: yes
    validate_certs: no
    headers:
      Cookie: "{{ login.cookies_string }}"
  register: devices
       
- name: search for mac in devices list and provision
  uri:
    url: https://{{ inventory_hostname }}:8443/api/s/default/cmd/devmgr
    method: POST
    body_format: json
    body:
      cmd: force-provision
      mac: "{{ item }}"
    validate_certs: no
    headers:
      Cookie: "{{ login.cookies_string }}"
  with_items: "{{ devices | community.general.json_query('*.data[*].mac') }}"
  register: mac