- name: Send email
  community.general.mail:
    host: {{ mailHost }}
    port: {{ mailSMTPPort }}
    username: {{ mailUsername }}
    password: {{ mailPassword }}
    to: {{ mailSendTo }}
    subject: Change wifi key
    body: Changed wifi key from {{ old_wifi_key }} to {{ wifi_key }}
  delegate_to: localhost
